# Generated by Django 3.2.16 on 2022-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
